plugin:
    name: 'arteriaweb.bugshop::lang.plugin.name'
    description: 'arteriaweb.bugshop::lang.plugin.description'
    author: Arteriaweb
    icon: oc-icon-bug
    homepage: ''
navigation:
    main-menu-item:
        label: Bugshop
        url: arteriaweb/bugshop/animals
        icon: icon-bug
        sideMenu:
            side-menu-item:
                label: Adatok
                url: arteriaweb/bugshop/datas
                icon: icon-list-ul
