title: Details
modelClass: Arteriaweb\Bugshop\Models\Detail
list: $/arteriaweb/bugshop/models/detail/columns.yaml
recordUrl: 'arteriaweb/bugshop/details/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
