title: Categories
modelClass: Arteriaweb\Bugshop\Models\Category
list: $/arteriaweb/bugshop/models/category/columns.yaml
recordUrl: 'arteriaweb/bugshop/categories/update/:slug'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
