name: Categories
modelClass: Arteriaweb\Bugshop\Models\Category
form: $/arteriaweb/bugshop/models/category/fields.yaml
defaultRedirect: arteriaweb/bugshop/categories
create:
    redirect: 'arteriaweb/bugshop/categories/update/:slug'
    redirectClose: arteriaweb/bugshop/categories
update:
    redirect: arteriaweb/bugshop/categories
    redirectClose: arteriaweb/bugshop/categories
preview: {  }
