name: Bugshops
modelClass: Arteriaweb\Bugshop\Models\Bugshop
form: $/arteriaweb/bugshop/models/bugshop/fields.yaml
defaultRedirect: arteriaweb/bugshop/bugshops
create:
    redirect: 'arteriaweb/bugshop/bugshops/update/:id'
    redirectClose: arteriaweb/bugshop/bugshops
update:
    redirect: arteriaweb/bugshop/bugshops
    redirectClose: arteriaweb/bugshop/bugshops
preview: {  }
