title: Helpers
modelClass: Arteriaweb\Bugshop\Models\Helper
list: $/arteriaweb/bugshop/models/helper/columns.yaml
recordUrl: 'arteriaweb/bugshop/helpers/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
